export default {
  FR: {
    COLORS: [
      'noir',
      'blanc',
      'bleu',
      'rouge',
      'jaune',
      'orange',
      'vert',
      'violet',
    ],
    SHAPES: ['carré', 'triangle', 'rectangle', 'cercle'],
    QUESTIONS: [
      "Couleur de l'arrière plan",
      "couleur d'arrière-plan du texte",
      'couleur de fond du texte de la forme',
      'couleur du nombre',
      'couleur de la forme',
      'texte en couleur',
      'texte de forme',
      'façonner',
    ],
    MISC: [
      'ET',
      'Trop vite? Entraînez-vous en changeant le temps du puzzle!',
      'ÉTABLISSEMENT DE LA CONNEXION',
      'FAIRE DES TRUCS DE HACKERMANS...',
      "CODE D'ACCÈS INDIQUÉ; NÉCESSITE UNE SAISIE CAPTCHA HUMAINE..",
      'le système a été contourné.',
      "Le système n'a pas accepté vos réponses",
      'la réponse était',
      'Bon travail, ',
      "Le temps s'est écoulé",
      'Tu as écrit',
    ],
  },
}
